# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dave Compton
email: davecompton7@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What I am doing, what I have done, and what I learned along the way.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://davecompton.net" # the base hostname & protocol for your site
twitter_username: dc1234
github_username:  dc25

github_comments_repository: dc25/myBlog-comments

# Build settings
markdown: kramdown
exclude: ["README.md", "Rakefile", "Gemfile", "Gemfile.lock"]
